-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE DATABASE collegesync;

-- SCHEMA PRINCIPAL ----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS collegesync AUTHORIZATION CURRENT_USER;

-- ============================================================
--  TABLE: users
-- ============================================================
CREATE TABLE IF NOT EXISTS collegesync.users
(
    id bigserial NOT NULL,
    name character varying(150) NOT NULL,
    email character varying(256) NOT NULL,
    birth_date date,
    hash_password character varying(256) NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc', NOW()),
    updated_at timestamp with time zone DEFAULT timezone('utc', NOW()),
    PRIMARY KEY (id)
);

-- ============================================================
--  TABLE: students
-- ============================================================
CREATE TABLE IF NOT EXISTS collegesync.students
(
    id bigserial PRIMARY KEY NOT NULL,
    registration_number character varying(20) NOT NULL,
    user_id bigint UNIQUE NOT NULL,
	FOREIGN KEY (user_id)
    	REFERENCES collegesync.users (id)
    	ON UPDATE NO ACTION
    	ON DELETE NO ACTION
);

-- ============================================================
--  TABLE: teachers
-- ============================================================
CREATE TABLE IF NOT EXISTS collegesync.teachers
(
    id bigserial PRIMARY KEY NOT NULL,
    user_id bigint UNIQUE NOT NULL,
    FOREIGN KEY (user_id)
    	REFERENCES collegesync.users (id)
    	ON UPDATE NO ACTION
    	ON DELETE NO ACTION
);

-- ============================================================
--  TABLE: subjects
-- ============================================================
CREATE TABLE IF NOT EXISTS collegesync.subjects
(
    id bigserial PRIMARY KEY NOT NULL,
	name character varying(100) NOT NULL,
    teacher_id bigint NOT NULL,
    FOREIGN KEY (teacher_id)
    	REFERENCES collegesync.teachers (id)
    	ON UPDATE NO ACTION
    	ON DELETE NO ACTION
	
);

-- ============================================================
--  TABLE: students_subjects
-- ============================================================
CREATE TABLE IF NOT EXISTS collegesync.students_subjects
(
    student_id bigserial NOT NULL,
    subject_id bigserial NOT NULL,
    PRIMARY KEY (student_id, subject_id),
	FOREIGN KEY (student_id)
    	REFERENCES collegesync.students (id)
    	ON UPDATE NO ACTION
    	ON DELETE NO ACTION,
	FOREIGN KEY (subject_id)
    	REFERENCES collegesync.subjects (id)
    	ON UPDATE NO ACTION
    	ON DELETE NO ACTION
);

-- ============================================================
--  TABLE: appointments_status
-- ============================================================
CREATE TABLE IF NOT EXISTS collegesync.appointments_status
(
    id bigserial NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

-- ============================================================
--  TABLE: appointments
-- ============================================================
CREATE TABLE IF NOT EXISTS collegesync.appointments
(
    id bigserial PRIMARY KEY NOT NULL,
    description character varying(256) NOT NULL,
    scheduled_at timestamp with time zone NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc', NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc', NOW()),
    appointments_status_id bigint NOT NULL,
    subject_id bigint NOT NULL,
    teacher_id bigint,
    student_id bigint,
	FOREIGN KEY (appointments_status_id)
    	REFERENCES collegesync.appointments_status (id)
    	ON UPDATE NO ACTION
    	ON DELETE NO ACTION,
	FOREIGN KEY (teacher_id)
	    REFERENCES collegesync.teachers (id)
	    ON UPDATE NO ACTION
	    ON DELETE NO ACTION,
	FOREIGN KEY (student_id)
	    REFERENCES collegesync.students (id)
	    ON UPDATE NO ACTION
	    ON DELETE NO ACTION,
	FOREIGN KEY (subject_id)
	    REFERENCES collegesync.subjects (id)
	    ON UPDATE NO ACTION
	    ON DELETE NO ACTION
	    NOT VALID
);

COMMIT;
