-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

-- Drop database collegesync;

CREATE DATABASE collegesync;

-- SCHEMA PRINCIPAL ----------------------------------------------------
USE collegesync;
CREATE SCHEMA IF NOT EXISTS collegesync;

USE collegesync;

-- ============================================================
--  TABLE: users
-- ============================================================
CREATE TABLE IF NOT EXISTS collegesync.users
(
    id bigint PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name varchar(150) NOT NULL,
    email varchar(256) UNIQUE NOT NULL,
    birth_date date,
    hash_password varchar(256) NOT NULL,
    created_at timestamp DEFAULT NOW(),
    updated_at timestamp DEFAULT NOW()
);

-- ============================================================
--  TABLE: admin
-- ============================================================
-- 1. Cria a tabela de admins
CREATE TABLE IF NOT EXISTS collegesync.admins (
    id bigint PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_id bigint UNIQUE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES collegesync.users (id)
    ON DELETE CASCADE
);

-- 2. Cria um usuário para ser o Admin (Senha: 1234)
-- (O hash abaixo é para '1234'. Se quiser outra, use o registro do site e depois insira o ID aqui)
INSERT INTO collegesync.users (name, email, hash_password, birth_date) 
VALUES ('Administrador', 'admin@college.com', '$2b$12$D.sXD5.a1J/k1J.k1J.k1J.k1J.k1J.k1J.k1J.k1J.k1J.k1J', '2000-01-01');

-- 3. Pega o ID desse usuário (supondo que seja o último inserido ou ID 7, verifique no seu banco!)
-- Vamos supor que o ID gerado foi 7.
INSERT INTO collegesync.admins (user_id) VALUES ((SELECT id FROM collegesync.users WHERE email = 'admin@college.com'));

-- ============================================================
--  TABLE: students
-- ============================================================
CREATE TABLE IF NOT EXISTS collegesync.students
(
    id bigint PRIMARY KEY AUTO_INCREMENT NOT NULL,
    registration_number varchar(20) UNIQUE NOT NULL,
    user_id bigint UNIQUE NOT NULL,
	FOREIGN KEY (user_id)
    	REFERENCES collegesync.users (id)
    	ON UPDATE NO ACTION
    	ON DELETE NO ACTION
);

-- ============================================================
--  TABLE: teachers
-- ============================================================
CREATE TABLE IF NOT EXISTS collegesync.teachers
(
    id bigint PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_id bigint UNIQUE NOT NULL,
    FOREIGN KEY (user_id)
    	REFERENCES collegesync.users (id)
    	ON UPDATE NO ACTION
    	ON DELETE NO ACTION
);

-- ============================================================
--  TABLE: subjects
-- ============================================================
CREATE TABLE IF NOT EXISTS collegesync.subjects
(
    id bigint PRIMARY KEY AUTO_INCREMENT NOT NULL,
	name varchar(100) NOT NULL,
    teacher_id bigint NOT NULL,
    FOREIGN KEY (teacher_id)
    	REFERENCES collegesync.teachers (id)
    	ON UPDATE NO ACTION
    	ON DELETE NO ACTION

);

-- ============================================================
--  TABLE: students_subjects
-- ============================================================
CREATE TABLE IF NOT EXISTS collegesync.students_subjects
(
    student_id bigint NOT NULL,
    subject_id bigint NOT NULL,
    PRIMARY KEY (student_id, subject_id),
	FOREIGN KEY (student_id)
    	REFERENCES collegesync.students (id)
    	ON UPDATE NO ACTION
    	ON DELETE NO ACTION,
	FOREIGN KEY (subject_id)
    	REFERENCES collegesync.subjects (id)
    	ON UPDATE NO ACTION
    	ON DELETE NO ACTION
);

-- ============================================================
--  TABLE: appointments_status
-- ============================================================
CREATE TABLE IF NOT EXISTS collegesync.appointments_status
(
    id bigint PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name varchar(50) NOT NULL
);

-- ============================================================
--  TABLE: appointments
-- ============================================================
CREATE TABLE IF NOT EXISTS collegesync.appointments
(
    id bigint PRIMARY KEY AUTO_INCREMENT NOT NULL,
    description varchar(256) NOT NULL,
    scheduled_at timestamp NOT NULL,
    notes text,
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),
    appointments_status_id bigint NOT NULL,
    subject_id bigint NOT NULL,
    teacher_id bigint,
    student_id bigint,
	FOREIGN KEY (appointments_status_id)
    	REFERENCES collegesync.appointments_status (id)
    	ON UPDATE NO ACTION
    	ON DELETE NO ACTION,
	FOREIGN KEY (teacher_id)
	    REFERENCES collegesync.teachers (id)
	    ON UPDATE NO ACTION
	    ON DELETE NO ACTION,
	FOREIGN KEY (student_id)
	    REFERENCES collegesync.students (id)
	    ON UPDATE NO ACTION
	    ON DELETE NO ACTION,
	FOREIGN KEY (subject_id)
	    REFERENCES collegesync.subjects (id)
	    ON UPDATE NO ACTION
	    ON DELETE NO ACTION
);

USE collegesync;

-- ============================================================
-- TABLE: users
-- ============================================================
INSERT INTO collegesync.users (name, email, birth_date, hash_password) VALUES
('Ana Souza', 'ana.souza@email.com', '2000-05-10', '$2a$12$a04siFMyPRjRzAFGXNzAved69STp0E7.2MPnVtCKWp03KuozrTcdO'),
('Bruno Lima', 'bruno.lima@email.com', '1999-08-22', '$2a$12$yyE/I0RGG11pk92KNDoROegXTeN2Z/huquhVhtoeVFbwJlQ7V.sEm'),
('Carlos Mendes', 'carlos.mendes@email.com', '1980-03-15', '$2a$12$hD778OoZ0KD.YG3quS5OA.ZdEYy7DQ3iZiK/mxERiWEOinMyeeymq'),
('Daniela Rocha', 'daniela.rocha@email.com', '1985-11-02', '$2a$12$/TCIU5XYQ6RzYs8y3y39MeoQSmb5Ai3qVKtEaoIWWGwZR3IgZja4a'),
('Eduardo Silva', 'eduardo.silva@email.com', '2001-01-18', '$2a$12$IcPI/RodgVdxn/SfJGLjmOFpOdHz2nphWMslu7e1I4J1NPKya5P1a'),
('Fernanda Alves', 'fernanda.alves@email.com', '1998-07-09', '$2a$12$Cc.j8A5VvhMevr8/Ik2RX.AMOn9IwvKL/zYeJhpYYby.WUvNOVxIu');

SELECT * FROM users;

-- ============================================================
-- TABLE: students
-- (usuários 1, 2, 5 e 6)
-- ============================================================
INSERT INTO collegesync.students (registration_number, user_id) VALUES
('2023001', 1),
('2023002', 2),
('2023003', 5),
('2023004', 6);

SELECT * FROM students;

-- ============================================================
-- TABLE: teachers
-- (usuários 3, 4, 5 e 6)
-- ============================================================
INSERT INTO collegesync.teachers (user_id) VALUES
(3),
(4),
(5),
(6);


-- ============================================================
-- TABLE: subjects
-- ============================================================
INSERT INTO collegesync.subjects (name, teacher_id) VALUES
('Banco de Dados', 1),
('Engenharia de Software', 2),
('Programação Web', 3),
('Estruturas de Dados', 4);


-- ============================================================
-- TABLE: students_subjects
-- ============================================================
INSERT INTO collegesync.students_subjects (student_id, subject_id) VALUES
(1, 1),
(1, 2),
(2, 1),
(2, 3),
(3, 2),
(3, 3),
(4, 4),
(4, 1);


-- ============================================================
-- TABLE: appointments_status
-- ============================================================
INSERT INTO collegesync.appointments_status (name) VALUES
('Agendado'),
('Confirmado'),
('Cancelado'),
('Concluído');


-- ============================================================
-- TABLE: appointments
-- ============================================================
INSERT INTO collegesync.appointments
(description, scheduled_at, notes, appointments_status_id, subject_id, teacher_id, student_id)
VALUES
('Orientação sobre trabalho final',
 '2025-02-10 14:00:00',
 'Levar rascunho do projeto',
 1, 1, 1, 1),

('Dúvidas sobre prova',
 '2025-02-12 10:30:00',
 NULL,
 2, 2, 2, 2),

('Revisão de conteúdo',
 '2025-02-15 16:00:00',
 'Focar em listas e árvores',
 4, 4, 4, 4),

('Acompanhamento acadêmico',
 '2025-02-18 09:00:00',
 'Avaliar desempenho do aluno',
 1, 3, 3, 3);

SELECT * FROM appointments;

COMMIT;